//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFVisifireChartsTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFVisifireChartsTest.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ControlTemplate
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:vc=&quot;clr-namespace:Visifire.Charts;assembly=WPFVisifire.Charts&quot;
        ///    TargetType=&quot;vc:Chart&quot;&gt; &lt;Border x:Name=&quot;ChartBorder&quot; Background=&quot;Transparent&quot;&gt;
        ///    &lt;Grid Name=&quot;RootElement&quot;
        ///            Background=&quot;Yellow&quot; Width=&quot;Auto&quot; Height=&quot;Auto&quot;
        ///            Margin=&quot;0,0,0,0&quot; &gt;
        ///    &lt;/Grid&gt;&lt;/Border&gt;&lt;/ControlTemplate&gt;.
        /// </summary>
        internal static string Chart_ApplyTemplate {
            get {
                return ResourceManager.GetString("Chart_ApplyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vc:Chart Height=&quot;300&quot; Width=&quot;400&quot; Margin=&quot;0,0,0,0&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///xmlns:vc=&quot;clr-namespace:Visifire.Charts;assembly=WPFVisifire.Charts&quot;&gt;
        ///         	&lt;vc:Chart.AxesX&gt;&lt;vc:Axis Interval=&quot;10&quot; AxisMinimum=&quot;1&quot; AxisMaximum=&quot;100&quot; /&gt;&lt;/vc:Chart.AxesX&gt; &lt;vc:Chart.AxesY&gt;&lt;vc:Axis AxisMaximum=&quot;200&quot; AxisMinimum=&quot;0&quot; Interval=&quot;20&quot;/&gt;&lt;/vc:Chart.AxesY&gt; &lt;vc:Chart.Series&gt;&lt;vc:DataSeries&gt;&lt;vc:DataSeries.DataPoints&gt;&lt;vc:DataPoint AxisXLabel=&quot;a&quot; XValue=&quot;10&quot; YValue=&quot;10&quot;/&gt;&lt;vc:DataPoint  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chart_AxisXaml {
            get {
                return ResourceManager.GetString("Chart_AxisXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ControlTemplate
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:vc=&quot;clr-namespace:Visifire.Charts;assembly=WPFVisifire.Charts&quot;
        ///    TargetType=&quot;vc:Chart&quot;&gt; &lt;Border x:Name=&quot;ChartBorder&quot; Background=&quot;Transparent&quot;&gt;
        ///    &lt;Grid x:Name=&quot;RootElement&quot;
        ///            Background=&quot;Red&quot; Width=&quot;Auto&quot; Height=&quot;Auto&quot;
        ///            Margin=&quot;0,0,0,0&quot; &gt;
        ///    &lt;/Grid&gt; &lt;/Border&gt;&lt;/ControlTemplate&gt;.
        /// </summary>
        internal static string Chart_CustomTemplate {
            get {
                return ResourceManager.GetString("Chart_CustomTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vc:DataSeries xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; xmlns:vc=&quot;clr-namespace:Visifire.Charts;assembly=WPFVisifire.Charts&quot;&gt;&lt;vc:DataSeries.DataPoints&gt;&lt;vc:DataPoint XValue=&quot;1&quot; YValue=&quot;10&quot;/&gt;&lt;vc:DataPoint XValue=&quot;2&quot; YValue=&quot;20&quot;/&gt;&lt;vc:DataPoint XValue=&quot;3&quot; YValue=&quot;15&quot;/&gt;&lt;vc:DataPoint XValue=&quot;4&quot; YValue=&quot;30&quot;/&gt;&lt;vc:DataPoint XValue=&quot;5&quot; YValue=&quot;20&quot;/&gt;&lt;/vc:DataSeries.DataPoints&gt;&lt;/vc:DataSeries&gt;.
        /// </summary>
        internal static string Chart_DefaultDataSeries {
            get {
                return ResourceManager.GetString("Chart_DefaultDataSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vc:Chart Height=&quot;300&quot; Width=&quot;400&quot; Margin=&quot;0,0,0,0&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///xmlns:vc=&quot;clr-namespace:Visifire.Charts;assembly=WPFVisifire.Charts&quot;&gt;
        ///         	&lt;vc:Chart.Titles&gt;
        ///                          &lt;vc:Title HorizontalAlignment=&quot;Center&quot; FontSize=&quot;18&quot; FontColor=&quot;#FFD6C8C8&quot; Background=&quot;#FF934141&quot;/&gt;
        ///        	&lt;/vc:Chart.Titles&gt; &lt;vc:Chart.Series&gt;&lt;vc:DataSeries&gt;&lt;vc:DataSeries.DataPoints&gt;&lt;vc:DataPoint XValue=&quot;1&quot; YValue=&quot;10&quot;/&gt;&lt;vc:DataPoint XValue=&quot;2&quot; YValue=&quot;20&quot;/&gt;&lt;vc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chart_DefaultXaml {
            get {
                return ResourceManager.GetString("Chart_DefaultXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ControlTemplate
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:vc=&quot;clr-namespace:Visifire.Charts;assembly=WPFVisifire.Charts&quot;
        ///    TargetType=&quot;vc:Chart&quot;&gt; 
        ///    &lt;Grid
        ///            Background=&quot;Yellow&quot; Width=&quot;Auto&quot; Height=&quot;Auto&quot;
        ///            Margin=&quot;0,0,0,0&quot; &gt;
        ///    &lt;Border Background=&quot;Transparent&quot; Width=&quot;Auto&quot; Height=&quot;Auto&quot;  /&gt;&lt;StackPanel Canvas.ZIndex=&quot;9000&quot; Name=&quot;CenterPanel&quot; Background=&quot;Transparent&quot; Width=&quot;500&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chart_EmptyTemplate {
            get {
                return ResourceManager.GetString("Chart_EmptyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vc:Chart Height=&quot;300&quot; Width=&quot;400&quot; Margin=&quot;0,0,0,0&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///xmlns:vc=&quot;clr-namespace:Visifire.Charts;assembly=WPFVisifire.Charts&quot;&gt;
        ///         	&lt;vc:Chart.Titles&gt;
        ///                          &lt;vc:Title Text=&quot;Chart Title&quot; HorizontalAlignment=&quot;Center&quot; FontSize=&quot;18&quot; FontColor=&quot;#FFD6C8C8&quot; Background=&quot;#FFF54E4E&quot; /&gt;
        ///        	&lt;/vc:Chart.Titles&gt;
        ///        &lt;/vc:Chart&gt;.
        /// </summary>
        internal static string Chart_TitleContentPropertyXaml {
            get {
                return ResourceManager.GetString("Chart_TitleContentPropertyXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vc:Chart Height=&quot;400&quot; Width=&quot;600&quot; Margin=&quot;0,0,0,0&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///xmlns:vc=&quot;clr-namespace:Visifire.Charts;assembly=WPFVisifire.Charts&quot;&gt;
        ///&lt;/vc:Chart&gt;.
        /// </summary>
        internal static string Chart_Xaml {
            get {
                return ResourceManager.GetString("Chart_Xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vc:DataSeries RenderAs=&quot;Column&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;  xmlns:vc=&quot;clr-namespace:Visifire.Charts;assembly=WPFVisifire.Charts&quot;&gt;&lt;vc:DataSeries.DataPoints&gt;&lt;vc:DataPoint XValue=&quot;1&quot; YValue=&quot;10&quot;/&gt;&lt;vc:DataPoint XValue=&quot;2&quot; YValue=&quot;20&quot;/&gt;&lt;vc:DataPoint XValue=&quot;3&quot; YValue=&quot;15&quot;/&gt;&lt;vc:DataPoint XValue=&quot;4&quot; YValue=&quot;30&quot;/&gt;&lt;vc:DataPoint XValue=&quot;5&quot; YValue=&quot;20&quot;/&gt;&lt;vc:DataPoint XValue=&quot;6&quot; YValue=&quot;20&quot;/&gt;&lt;vc:DataPoint XValue=&quot;7&quot; YValue=&quot;20&quot;/&gt;&lt;vc:DataPoint XValue=&quot;8&quot; YValue=&quot;20&quot;/&gt;&lt;vc:DataPoint [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataSeries_BigXaml {
            get {
                return ResourceManager.GetString("DataSeries_BigXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vc:DataSeries xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///xmlns:vc=&quot;clr-namespace:Visifire.Charts;assembly=WPFVisifire.Charts&quot; XValueType=&quot;DateTime&quot;&gt;&lt;vc:DataSeries.DataPoints&gt;&lt;vc:DataPoint XValue=&quot;1/1/2001&quot; YValue=&quot;10&quot;/&gt;&lt;vc:DataPoint XValue=&quot;2/1/2001&quot; YValue=&quot;20&quot;/&gt;&lt;vc:DataPoint XValue=&quot;3/1/2001&quot; YValue=&quot;15&quot;/&gt;&lt;vc:DataPoint XValue=&quot;4/1/2001&quot; YValue=&quot;30&quot;/&gt;&lt;vc:DataPoint XValue=&quot;5/1/2001&quot; YValue=&quot;20&quot;/&gt;&lt;vc:DataPoint XValue=&quot;8/1/2001&quot; YValue=&quot;20&quot;/&gt;&lt;/vc:DataSeries.DataPoints&gt;&lt;/vc:DataSeries [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DateTimeXaml {
            get {
                return ResourceManager.GetString("DateTimeXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Title.
        /// </summary>
        internal static string Title_ShortText {
            get {
                return ResourceManager.GetString("Title_ShortText", resourceCulture);
            }
        }
    }
}
